<?php

$_COS_LANG_MODULE['domain_deleted_action_message'] = 'Domæne er blevet slettet';
$_COS_LANG_MODULE['domain_added'] = 'Domæne tilføjet';
$_COS_LANG_MODULE['domain_delete_info'] = 'Slet tilknyttet domæne: {DOMAIN}';
$_COS_LANG_MODULE['domain_confirm_delete_legend'] = 'Bekræft sletning';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = 'Du kan kune knytte domæner til et master domæne';
$_COS_LANG_MODULE['domain_info_allow_create_ip'] = '
    Du kan tilknytte et selv valgt domæne navn, 
    hvis du har kontrol over dit domænes navne server. 
    Denne servers konfiguration genstartes en gang hver time,
    så du vil ikke altid kunne se ændringerne med det samme.<br />
    Vær ligeledes opmærksom på at der kan gå op til et døgn førend 
    en navne server sender alle forespørgelser rette vej.<br />
    For at dit domæne navn skal vise samme sider
    som denne URL,
    skal du lade en record (typisk en type A) pege på følgende IP: ';
$_COS_LANG_MODULE['domain_add_domain'] = 'Tilføj domæne';
$_COS_LANG_MODULE['domain_info_allow_create'] = "Du kan oprette et domæne som vil dække over det eksisterer navn {HOST_NAME}. 
    Domæne navnet skal skrives i formen 'eksempel.dk' eller 'www.eksempel.dk'. Fx 'test.eksempel.dk'. Karakterne 'a-z' og '0-9' samt '-' er tilladte. 
    <b>Det er kun tilladt med et domæne tilknyttet!</b>";
$_COS_LANG_MODULE['domain_info_deny_create'] = 'Du kan ikke oprettet domæne';
$_COS_LANG_MODULE['domain_error_not_valid_name'] = 'Ikke et gyldig domæne navn';
$_COS_LANG_MODULE['domain_error_no_master_config'] = 'Ingen master configuration';
$_COS_LANG_MODULE['domain_hostname_exists'] = 'Domæne navnet eksisterer allerede';
