<?php


$_COS_LANG_MODULE['domain_confirm_delete_legend'] = 'Bekræft sletning';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = 'Du kan kune knytte domæner til et master domæne';
$_COS_LANG_MODULE['domain_info_deny_create'] = 'Du kan ikke oprettet domæne';
$_COS_LANG_MODULE['domain_hostname_exists'] = 'Domæne navnet eksisterer allerede';
$_COS_LANG_MODULE['domain_add_domain'] = 'Tilføj domæne';
// Translation of file ./modules/domain/index.php

$_COS_LANG_MODULE['domain_deleted_action_message'] = 'Domæne er blevet slettet';
$_COS_LANG_MODULE['domain_added'] = 'Domæne tilføjet';


$_COS_LANG_MODULE['domain_info_allow_create'] = "Du kan oprette et domæne som vil dække over det eksisterer navn (%1%). 
    Domæne navnet skal skrives i formen 'eksempel.dk' eller 'www.eksempel.dk'. Fx 'test.eksempel.dk'. Karakterne 'a-z' og '0-9' samt '-' er tilladte. 
    <b>Det er kun tilladt med et domæne tilknyttet!</b>";



$_COS_LANG_MODULE['domain_info_allow_create_ip'] = 'For at dit domæne skal vises skal du lade en tilsvarende A record i din navne server pege på følgende IP: ';
$_COS_LANG_MODULE['domain_delete_info'] = 'Slet tilknyttet domæne: %1%';

$_COS_LANG_MODULE['domain_delete_domain'] = 'Slet domæne';
