<?php

$_COS_LANG_MODULE['domain_deleted_action_message'] = '域已被删除';
$_COS_LANG_MODULE['domain_added'] = '域已被添加';
$_COS_LANG_MODULE['domain_delete_info'] = '域名：{域}';
$_COS_LANG_MODULE['domain_confirm_delete_legend'] = '删除域';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = '你只能一个域添加到主域';
$_COS_LANG_MODULE['domain_info_allow_create_ip'] = '你需要一个DNS A记录指向到这个地址';
$_COS_LANG_MODULE['domain_add_domain'] = '添加域';
$_COS_LANG_MODULE['domain_info_allow_create'] = '您可以为您的网站<b>{} HOST_NAME</b>添加域名。该域名必须是像“example.com”或“www.example.com”。例如：“test.example.com”。字符“AZ”OG“0-9”和“ - ”。 <b>只</b>允许<b>一个域名允许</b>';
$_COS_LANG_MODULE['domain_info_deny_create'] = '你不能创建一个域';
$_COS_LANG_MODULE['domain_error_not_valid_name'] = '不是有效的名称';
$_COS_LANG_MODULE['domain_error_no_master_config'] = '无主的配置被发现';
$_COS_LANG_MODULE['domain_hostname_exists'] = '主机名存在';
