<?php

// Translation of file ./modules/domain/create.php


$_COS_LANG_MODULE['domain_confirm_delete_legend'] = 'Confirm to delete domain';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = 'You can only add a domain to a master domain';
$_COS_LANG_MODULE['domain_info_deny_create'] = 'Your can not create a domain';
$_COS_LANG_MODULE['domain_hostname_exists'] = 'Hostname exists';
$_COS_LANG_MODULE['domain_add_domain'] = 'Add domain';
// Translation of file ./modules/domain/index.php

$_COS_LANG_MODULE['domain_deleted_action_message'] = 'Domain has been deleted';
$_COS_LANG_MODULE['domain_added'] = 'Domain has been added';

$_COS_LANG_MODULE['domain_info_allow_create'] = "You can add a domain name for your website (%1%). 
    The name of the domain must be like 'eksample.com' og 'www.example.com'. E.g.: 'test.example.com'. Characters 'a-z' og '0-9' and '-' are allowed. 
    <b>Only one domain name allowed</b>";

$_COS_LANG_MODULE['domain_delete_domain'] = 'Deleted domain';
$_COS_LANG_MODULE['domain_info_allow_create_ip'] = 'You need a DNS A record pointing to this address';
$_COS_LANG_MODULE['domain_error_not_valid_name'] = 'Not a valid name';
$_COS_LANG_MODULE['domain_error_no_master_config'] = 'No master config was found';
