<?php


// Translation of file /modules/domain/module.php

$_COS_LANG_MODULE['domain_deleted_action_message'] = 'Domain has been deleted';
$_COS_LANG_MODULE['domain_added'] = 'Domain has been added';
$_COS_LANG_MODULE['domain_delete_info'] = 'Domain name: {DOMAIN}';
$_COS_LANG_MODULE['domain_confirm_delete_legend'] = 'Delete domain';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = 'You can only add a domain to a master domain';
$_COS_LANG_MODULE['domain_info_allow_create_ip'] = 'You need a DNS A record pointing to this address';
$_COS_LANG_MODULE['domain_add_domain'] = 'Add domain';
$_COS_LANG_MODULE['domain_info_allow_create'] = "You can add a domain name for your website <b>{HOST_NAME}</b>. 
    The name of the domain must be like 'example.com' or 'www.example.com'. E.g.: 'test.example.com'. Characters 'a-z' og '0-9' and '-' are allowed. 
    <b>Only one domain name allowed</b>";
$_COS_LANG_MODULE['domain_info_deny_create'] = 'Your can not create a domain';
$_COS_LANG_MODULE['domain_error_not_valid_name'] = 'Not a valid name';
$_COS_LANG_MODULE['domain_error_no_master_config'] = 'No master config was found';
$_COS_LANG_MODULE['domain_hostname_exists'] = 'Hostname exists';
