<?php

// Translation of file ./modules/domain/create.php

$_COS_LANG_MODULE['siteclone_rpc_ini_file_exists'] = 'siteclone_rpc_ini_file_exists';
$_COS_LANG_MODULE['siteclone_rpc_could_not_make_ini_file'] = 'siteclone_rpc_could_not_make_ini_file';
$_COS_LANG_MODULE['siteclone_rpc_ini_file_created'] = 'siteclone_rpc_ini_file_created';
// Translation of file ./modules/domain/model.domain.inc

$_COS_LANG_MODULE['domain_confirm_delete_legend'] = 'domain_confirm_delete_legend';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = 'domain_can_not_add_domain_to_non_master';
$_COS_LANG_MODULE['domain_info_deny_create'] = 'domain_info_deny_create';
$_COS_LANG_MODULE['domain_hostname_exists'] = 'domain_hostname_exists';
$_COS_LANG_MODULE['domain_add_domain'] = 'domain_add_domain';
// Translation of file ./modules/domain/index.php

$_COS_LANG_MODULE['domain_deleted_action_message'] = 'domain_deleted_action_message';
$_COS_LANG_MODULE['domain_added'] = 'domain_added';
