<?php

$_COS_LANG_MODULE['domain_deleted_action_message'] = 'Domain er slettet';
$_COS_LANG_MODULE['domain_added'] = 'Domenet har blitt lagt';
$_COS_LANG_MODULE['domain_delete_info'] = 'Domenenavn: {DOMAIN}';
$_COS_LANG_MODULE['domain_confirm_delete_legend'] = 'Slett domene';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = 'Du kan bare legge til et domene til en master domene';
$_COS_LANG_MODULE['domain_info_allow_create_ip'] = 'Du trenger en DNS En rekord som peker til denne adressen';
$_COS_LANG_MODULE['domain_add_domain'] = 'Legg domene';
$_COS_LANG_MODULE['domain_info_allow_create'] = 'Du kan legge til et domenenavn for ditt nettsted <b>{HOST_NAME}.</b> Navnet på domenet må være som &quot;example.com&quot; eller &quot;www.example.com &#39;. For eksempel: &#39;test.example.com&#39;. Tegnene &#39;az&#39; og &#39;0-9&#39; og &#39;-&#39;. Tillates <b>kun ett domenenavn tillatt</b>';
$_COS_LANG_MODULE['domain_info_deny_create'] = 'Din kan ikke opprette et domene';
$_COS_LANG_MODULE['domain_error_not_valid_name'] = 'Ikke et gyldig navn';
$_COS_LANG_MODULE['domain_error_no_master_config'] = 'Ingen mester config ble funnet';
$_COS_LANG_MODULE['domain_hostname_exists'] = 'Vertsnavn finnes';
