<?php

$_COS_LANG_MODULE['domain_deleted_action_message'] = 'Domäne gelöscht wurde';
$_COS_LANG_MODULE['domain_added'] = 'Domain hinzugefügt wurde';
$_COS_LANG_MODULE['domain_delete_info'] = 'Domain-Namen: {DOMAIN}';
$_COS_LANG_MODULE['domain_confirm_delete_legend'] = 'Domain löschen';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = 'Sie können nur eine Domain zu einem Master-Domäne hinzufügen';
$_COS_LANG_MODULE['domain_info_allow_create_ip'] = 'Sie benötigen einen DNS-A-Eintrag, der auf dieser Adresse';
$_COS_LANG_MODULE['domain_add_domain'] = 'Domäne hinzufügen';
$_COS_LANG_MODULE['domain_info_allow_create'] = 'Sie können einen Domain-Namen für Ihre Website <b>{HOST_NAME}</b> hinzuzufügen. Der Name der Domäne muss wie &quot;example.com&quot; oder &quot;www.example.com&quot; sein. ZB: &#39;test.example.com&#39;. Charaktere &quot;az&quot; og &quot;0-9&quot; und &quot;-&quot;. Dürfen <b>nur ein Domain-Namen erlaubt</b>';
$_COS_LANG_MODULE['domain_info_deny_create'] = 'Sie können keine Domäne erstellen';
$_COS_LANG_MODULE['domain_error_not_valid_name'] = 'Kein gültiger Name';
$_COS_LANG_MODULE['domain_error_no_master_config'] = 'Kein Master Config wurde festgestellt,';
$_COS_LANG_MODULE['domain_hostname_exists'] = 'Hostname existiert,';
