<?php

$_COS_LANG_MODULE['domain_deleted_action_message'] = 'Domain on poistettu';
$_COS_LANG_MODULE['domain_added'] = 'Domain on lisätty';
$_COS_LANG_MODULE['domain_delete_info'] = 'Verkkotunnus: {DOMAIN}';
$_COS_LANG_MODULE['domain_confirm_delete_legend'] = 'Poista verkkotunnuksen';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = 'Voit lisätä vain toimialueen päällikkö domain';
$_COS_LANG_MODULE['domain_info_allow_create_ip'] = 'Tarvitset DNS ennätys osoittaa tähän osoitteeseen';
$_COS_LANG_MODULE['domain_add_domain'] = 'Lisää domain';
$_COS_LANG_MODULE['domain_info_allow_create'] = 'Voit lisätä verkkotunnus sivustosi <b>{HOST_NAME}.</b> Toimialueen nimi on kuin &quot;example.com&quot; tai &quot;www.example.com&quot;. Esim: &quot;test.example.com&quot;. Merkit &quot;az&quot; og &quot;0-9&quot; ja &quot;-&quot; ovat sallittuja. <b>Vain yksi verkkotunnus sallittu</b>';
$_COS_LANG_MODULE['domain_info_deny_create'] = 'Sinun voi luoda toimialueen';
$_COS_LANG_MODULE['domain_error_not_valid_name'] = 'Ei oikea nimi';
$_COS_LANG_MODULE['domain_error_no_master_config'] = 'Ei isäntä config löytyi';
$_COS_LANG_MODULE['domain_hostname_exists'] = 'Hostname olemassa';
