<?php

$_COS_LANG_MODULE['domain_deleted_action_message'] = 'Domän har tagits bort';
$_COS_LANG_MODULE['domain_added'] = 'Domän har lagts';
$_COS_LANG_MODULE['domain_delete_info'] = 'Domännamn: {DOMAIN}';
$_COS_LANG_MODULE['domain_confirm_delete_legend'] = 'Radera domän';
$_COS_LANG_MODULE['domain_can_not_add_domain_to_non_master'] = 'Du kan bara lägga till en domän till en master-domän';
$_COS_LANG_MODULE['domain_info_allow_create_ip'] = 'Du behöver en DNS A-record som pekar till denna adress';
$_COS_LANG_MODULE['domain_add_domain'] = 'Lägg domän';
$_COS_LANG_MODULE['domain_info_allow_create'] = 'Du kan lägga till ett domännamn för din webbplats <b>{HOST_NAME}.</b> Namnet på domänen måste vara som &quot;example.com&quot; eller &quot;www.example.com&quot;. T.ex: &quot;test.example.com&quot;. Tecken &quot;az&quot; og &quot;0-9&quot; och &quot;-&quot;. Tillåts <b>Endast ett domännamn tillåts</b>';
$_COS_LANG_MODULE['domain_info_deny_create'] = 'Din kan inte skapa en domän';
$_COS_LANG_MODULE['domain_error_not_valid_name'] = 'Inte ett giltigt namn';
$_COS_LANG_MODULE['domain_error_no_master_config'] = 'Ingen huvud config befanns';
$_COS_LANG_MODULE['domain_hostname_exists'] = 'Värdnamn existerar';
